### PR TITLE
czech translation for obs kinect plugin (based on english and FR file…

### PR DESCRIPTION
**Pull request by BobTape**
czech translation for obs kinect plugin (based on english and FR files), i try undestand meaning and write it logicaly.

thanx SirLynx

### CODE REVIEW

**Comment by SirLynix** [comment]
Thank you!

**Comment by BobTape** [comment]
you are welcome.
For now, just a translation until I understand how it works: D

**Comment by SirLynix** [comment]
I'm here if you have any question on obs-kinect internals. For now I'm working on other projects but I'll come back soon to obs-kinect.

**Comment by BobTape** [comment]
I today will study some time your code, for better undestanding :)

**Pull request merged**
